import React, { useState, useRef, useEffect } from "react";
import { FaPause, FaPlay, FaVolumeMute, FaVolumeUp, FaExpand } from "react-icons/fa";
import Navbar from '../../../common/Navbar';
import Footer from './layout/Footer';
import HeroSection from './sections/HeroSection';
import MonitoringSection from './sections/MonitoringSection';
import SpecificationsSection from './sections/SpecificationsSection';
import CTASection from './sections/CTASection';

function SolarPanel() {
        const [activeIndex, setActiveIndex] = useState(0);
        const [isPlaying, setIsPlaying] = useState(true);
        const [progress, setProgress] = useState(0);
        const [isMuted, setIsMuted] = useState(true);
        const videoRef = useRef(null);
    const videoData = [
        {
          src: "https://digitalassets.tesla.com/tesla-contents/video/upload/f_auto,q_auto:best/powerwall-store-use-save-carousel-01.mp4",
          title: "Store Extra Energy",
          description: "When your solar system generates more energy than you need, you can store the extra energy with Powerwall and save it for later. Powerwall can also recharge from the grid when utility prices are low."
        },
        {
          src: "https://digitalassets.tesla.com/tesla-contents/video/upload/f_auto,q_auto:best/powerwall-store-use-save-carousel-02.mp4",
          title: "Use Energy",
          description: "Your stored energy is available whenever you need it—during the day, at night or when an outage occurs. A Powerwall system can power your entire home, including your heater or A/C, as well as other large appliances."
        },
        {
          src: "https://digitalassets.tesla.com/tesla-contents/video/upload/f_auto,q_auto:best/powerwall-store-use-save-carousel-03.mp4",
          title: "Save and Earn",
          description: "Using your usage history, weather forecasts and utility price estimates, Powerwall optimizes your stored energy to power your home more efficiently, day and night. With some utilities, you can earn money by selling your energy to the grid."
        },
      ];
      const videoFeatureData = [
        {
          title: 'Simple Aesthetic',
          description:
            'Panels and skirts are all black, creating a uniform, monochromatic look.',
          image: "https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/solar-panels-carousel-01-desktop",
        },
        {
          title: 'Weather Resistant',
          description:
            'Installation points are sealed to protect against rain, snow and ice.',
          image: "https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/solar-panels-carousel-02-desktop",
        },
        {
          title: 'Easy Installation',
          description:
            'Proprietary hardware and streamlined installation help to minimize impact to your roof.',
          image: "https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/solar-panels-carousel-03-desktop",
        },
        {
          title: 'Low Profile',
          description:
            'Rail-free mounting keeps panels close to your roof and panel skirts hide hardware and edges from view.',
          image: "https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/solar-panels-carousel-04-desktop",
        },
      ];
          const togglePlay = () => {
            if (videoRef.current.paused) {
              videoRef.current.play();
              setIsPlaying(true);
            } else {
              videoRef.current.pause();
              setIsPlaying(false);
            }
          };
        
          const toggleMute = () => {
            videoRef.current.muted = !videoRef.current.muted;
            setIsMuted(videoRef.current.muted);
          };
        
          const toggleFullscreen = () => {
            videoRef.current.requestFullscreen?.();
          };
        
          const handleTimeUpdate = () => {
            const percent = (videoRef.current.currentTime / videoRef.current.duration) * 100;
            setProgress(percent);
          };
        
          useEffect(() => {
            videoRef.current.load();
            videoRef.current.play();
            setIsPlaying(true);
          }, [activeIndex]);
        
  return (
    <div className="app">
      <Navbar />
      <main>
        <HeroSection />
        {/* Text and image section */}
        <div className="flex flex-col justify-center items-center">
{/* Text */}
<div className="max-w-4xl mx-auto mt-10 text-center">
  <h2 className="text-2xl sm:text-3xl font-semibold mb-4">
    Power Your Home, Save Money
  </h2>
  <p className="text-gray-700 text-base sm:text-lg">
    Powerwall is a compact home battery that stores energy generated by solar or from the grid. 
    You can then use your stored energy to power the devices and appliances in your home day and night, 
    during outages or when you want to go off-grid. With customizable power modes, 
    you can optimize your stored energy for outage protection, electricity bill savings and more.
  </p>
</div>

            {/* Image */}
                <div>
                    <img
                        src="https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/price-solar-desktop"
                        alt="Solar Panel"
                        className="w-full h-full object-cover"
                    />
                </div>
        </div>
    {/* Hero Video section */} 
<div className="relative w-full h-screen flex flex-col items-center justify-center bg-black">
  {/* Video Container */}
  <div className="relative w-[75%] h-[60%] mx-auto overflow-hidden rounded-xl shadow-lg">
    <video
      ref={videoRef}
      className="w-full h-full object-cover"
      autoPlay
      loop
      muted={isMuted}
      playsInline
      onTimeUpdate={handleTimeUpdate}
    >
      <source src={videoData[activeIndex].src} type="video/mp4" />
      Your browser does not support the video tag.
    </video>

    {/* Overlay
    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent"></div> */}

    
  </div>

  {/* Pagination Dots */}
  <div className="flex space-x-2 mt-4">
    {videoData.map((_, index) => (
      <div
        key={index}
        className={`w-2.5 h-2.5 rounded-full transition-all cursor-pointer ${
          activeIndex === index ? "bg-white scale-110" : "bg-gray-400"
        }`}
        onClick={() => setActiveIndex(index)}
      ></div>
    ))}
  </div>

  {/* Text Content */}
  <div className="text-center text-white mt-6 max-w-xl">
    <h2 className="text-2xl font-bold">{videoData[activeIndex].title}</h2>
    <p className="text-sm mt-2 text-gray-300">{videoData[activeIndex].description}</p>
  </div>
</div>
<div className="bg-black text-white py-12 ">
  {/* Image and Text Container */}
  <div className=" w-full mx-auto flex flex-col items-center md:items-start gap-10">
    
    {/* Image */}
    <div className="w-full md:w-full">
      <img
        src="https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/storms-happen-desktop" // replace with actual image path
        alt="Solar Panels on Roof"
        className="rounded-lg shadow-lg w-full object-cover"
      />
    </div>

{/* Text */}
<div className="w-full text-center max-w-7xl mx-auto">
  <h2 className="text-3xl md:text-2xl font-semibold mb-4">
    Storms Happen—Outages Don’t Have To
  </h2>
  <p className="text-gray-300 text-lg leading-relaxed">
    Keep your home and all appliances powered during an outage. When severe weather is forecast, 
    Storm Watch will automatically charge Powerwall to its maximum capacity to prepare for an outage. 
    When an outage occurs, Powerwall will help keep your solar system running or, if using grid power, 
    will transition your home to stored energy instantly.
  </p>
</div>

  </div>
</div>
        <MonitoringSection />
        {/*  */}
<div className="bg-black text-white py-12 ">
  {/* Image and Text Container */}
  <div className=" w-full mx-auto flex flex-col items-center md:items-start gap-10">
    
    {/* Image */}
    <div className="w-full md:w-full">
      <img
        src="https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/energy-thats-there-desktop" // replace with actual image path
        alt="Solar Panels on Roof"
        className="rounded-lg shadow-lg w-full object-cover"
      />
    </div>

{/* Text */}
<div className="w-full text-center max-w-7xl mx-auto">
  <h2 className="text-3xl md:text-2xl font-semibold mb-4">
  Energy That’s There When You Need It
  </h2>
  <p className="text-gray-300 text-lg leading-relaxed">
  Backup protection only works when your backup system is reliable. Powerwall is a home battery system that can be charged from solar panels or the grid and is designed to withstand extreme weather conditions and harsh environments with minimal service or maintenance. It can maintain normal operation in cold temperatures, high humidity and flooding in two feet of water. With Heat Mode, Powerwall heats itself intelligently to maintain optimal charge and discharge performance in temperatures as low as -4°F. View Heat Mode White Paper
  </p>
</div>

  </div>
</div>
{/*  */}
<div className="bg-black text-white py-12 ">
  {/* Image and Text Container */}
  <div className="max-w-7xl mx-auto flex flex-col items-center md:items-start gap-10">
    
    {/* Image */}
    <div className="w-full md:w-full">
      <img
        src="https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/charge-on-solar-desktop" 
        alt="Solar Panels on Roof"
        className="rounded-lg shadow-lg w-full object-cover"
      />
    </div>

{/* Text */}
<div className="w-full text-center max-w-7xl mx-auto">
  <h2 className="text-3xl md:text-2xl font-semibold mb-4">
  Charge on Solar
  </h2>
  <p className="text-gray-300 text-lg leading-relaxed">
  Powerwall backup protection extends beyond the home. You can optimize your stored energy to charge your electric vehicle with clean energy during the day, at night or during an outage. Adjust your system settings to charge exclusively with excess solar energy or share your electric vehicle’s battery power with your home using Powershare to extend your home’s backup support during an outage
  </p>
</div>

  </div>
</div>

        <SpecificationsSection />
        <CTASection />
      </main>
      <Footer />
    </div>
  );
}

export default SolarPanel;
